name: Main Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  choose-workflow:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.set_frontend.outputs.frontend }}
      backend: ${{ steps.set_backend.outputs.backend }}
    steps:
      - name: Set up Frontend
        id: set_frontend
        run: echo "::set-output name=frontend::false"
      - name: Set up Backend
        id: set_backend
        run: echo "::set-output name=backend::false"
      - name: Check for frontend changes
        id: check_frontend_changes
        run: |
          # Check if there are changes in the frontend folder
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -qE '^apps/portal'; then
            echo "::set-output name=frontend::true"
          fi
      - name: Check for backend changes
        id: check_backend_changes
        run: |
          # Check if there are changes in the backend folder
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -qE '^apps/api'; then
            echo "::set-output name=backend::true"
          fi

  run-workflows:
    needs: choose-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Run Frontend Workflow
        if: needs.choose-workflow.outputs.frontend == 'true'
        run: echo "Run Frontend Workflow"
        # You can replace the echo command with the actual command to trigger the frontend workflow

      - name: Run Backend Workflow
        if: needs.choose-workflow.outputs.backend == 'true'
        run: echo "Run Backend Workflow"
        # You can replace the echo command with the actual command to trigger the backend workflow
